### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [SvOlli/retrocartdumper#3]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@ihsinme) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by SvOlli** [comment]
Hello Jamie,
this is a software project for a very specific niche use-case that as far as I can tell has close to zero installations. Since it's required to compile the software yourself, everyone using it does at least to have basic knowledge about running self-build software and it's risks.
So because of that I'm pretty sure it's better to discuss this security concern openly in this ticket.

**Comment by JamieSlome** [comment]
@SvOlli - completely understand :)

I have made the report public, which can be viewed here:
https://huntr.dev/bounties/1257df5a-54bc-4a58-ac71-1a83faa78dd2/

Let me know if you have any further questions or thoughts.

**Comment by SvOlli** [comment]
I get an error message: "This report is not public" when clicking on the link.

**Comment by JamieSlome** [comment]
@SvOlli - are you able to try in an Incognito window?

**Comment by SvOlli** [comment]
The problem was a browser plugin prohibiting execution of external JavaScript code.
The security concern is rather [one of those face-palm off-by-one coding errors](https://github.com/SvOlli/retrocartdumper/commit/e2379cbdad6b1c664435cfe2cf45cc2ebf65e57c#diff-a0cb465674c1b01a07d361f25a0ef2b0214b7dfe9412b7777f89add956da10ecR42-R43).
Note that in lines 29-30 it was done correctly. Nevertheless the bug is now fixed using memset.

Thanks for the find,
SvOlli

**Comment by JamieSlome** [comment]
@SvOlli - thanks for the feedback. I have shared it with the researcher on the report and marked the report as informative 👍
